## 安裝 爬蟲套件

In [2]:
! pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable


In [3]:
! pip install html5lib

Defaulting to user installation because normal site-packages is not writeable


In [13]:
import requests
from bs4 import BeautifulSoup

## BeautifulSoup Base
find() 只找第一個符合條件的

https://www.crummy.com/software/BeautifulSoup/bs4/doc.zh/#find-all

find_all() 找所有符合條件的

select_one() 只找一個符合條件的可直接使用css語法

select() 找所有符合條件的可使用css語法

In [27]:
import requests
from bs4 import BeautifulSoup

html='''<a id='a1' class="c1">V1</a>
<a id='a2' class="c1">V2</a>
<a id='a3' class="c3">V3</a>
'''
soup = BeautifulSoup(html,"html5lib")
print(soup.find(id="a1"))
print(soup.find(class_="c1"))
print(soup.find_all(class_="c1"))

print(soup.select_one("#a1"))
print(soup.select(".c1"))

<a class="c1" id="a1">V1</a>
<a class="c1" id="a1">V1</a>
[<a class="c1" id="a1">V1</a>, <a class="c1" id="a2">V2</a>]
<a class="c1" id="a1">V1</a>
[<a class="c1" id="a1">V1</a>, <a class="c1" id="a2">V2</a>]


In [30]:
import requests
from bs4 import BeautifulSoup
html='''<a id='a1' class="c1" href="https://google.com">Google</a>
<a id='a2' class="c1"  href="https://yahoo.com">Yahoo</a>
<a id='a3' class="c3" href="https://facebook.com">Facebook</a>
'''
soup = BeautifulSoup(html,"html5lib")
print(soup.find(id="a1").getText())
print(soup.find(id="a1").get("href"))
tmpList = soup.find_all(class_="c1")
for tag in tmpList:
    print(tag.get("href"),tag.getText())


Google
https://google.com
https://google.com Google
https://yahoo.com Yahoo


# 使用html檔案練習

In [31]:
import bs4
htmlFile = open('web1.html',encoding="utf8",errors='ignore')
objSoup = bs4.BeautifulSoup(htmlFile, 'html5lib')
print("以下是列印一個h1元素: ")
objTag = objSoup.find('h1')
print(objTag.text)
print("以下是列印全部h1元素: ")
objTag = objSoup.find_all('h1')
for data in objTag:                       
    print(data.text)
objTag = objSoup.find_all('h2', limit=2)
print("以下是列印h2元素，只找兩個: ")
for data in objTag:                       
    print(data.text)

以下是列印一個h1元素: 
class與id練習測試h1標籤
以下是列印全部h1元素: 
class與id練習測試h1標籤
國家首都資料表
h1標籤測試1
h1標籤測試2
h1標籤測試3
h1標籤測試4
以下是列印h2元素，只找兩個: 
class與id練習測試h2標籤
程式語言清單


## 查詢 css中的class方法2，請留意查詢結果。 標籤為span且class為class1


In [32]:
import bs4
htmlFile = open('web1.html',encoding="utf8",errors='ignore')
objSoup = bs4.BeautifulSoup(htmlFile, 'html5lib')
objTag = objSoup.find_all('span',class_='class1')
for data in objTag:                       
    print(data)
    print(data.text)


<span class="class1">各種</span>
各種


In [33]:
import bs4
htmlFile = open('web1.html',encoding="utf8",errors='ignore')
objSoup = bs4.BeautifulSoup(htmlFile, 'html5lib')
objTag = objSoup.find_all('div',{'class':{'class1','class2'}})
for data in objTag:                       
    print(data)
    print(data.text)

<div class="class1">故宮博物院</div>
故宮博物院
<div class="class2">日月潭</div>
日月潭
<div class="class2 class3">阿里山</div>
阿里山


## 標籤回傳內容

.string 會返回標籤最裡面的內容，如果標籤內還有其他子節點(若有子標籤，代表不是單純的字串)，而會輸出 None。

.strings 可以獲得多個內容，但需要加上迴圈進行資料查找處理。

.stripped_strings 可將輸出的字串中空白內容去除。 

repr(）方法可將物件或其他資料轉換為字串進行輸出!

In [39]:
import bs4
htmlFile = open('web1.html',encoding="utf8",errors='ignore')
objSoup = bs4.BeautifulSoup(htmlFile, 'html5lib')

# for string in objSoup.strings:
#     print(string) 

# print("-"*70)
# for string in objSoup.strings:
#     print(repr(string))


# for string in objSoup.stripped_strings:
#     print(repr(string))    
print("-"*70)
for data in objTag:                       
    print(data)
    print(data.string)

----------------------------------------------------------------------
<div class="class1">故宮博物院</div>
故宮博物院
<div class="class2">日月潭</div>
日月潭
<div class="class2 class3">阿里山</div>
阿里山


## 查找各種層級節點
### 子節點查找
標籤的 .content 屬性可以將標籤的子節點以 list 的方式輸出。

.children 返回的不是一個 list，不過我們可以透過這個屬性找到所有子節點。

.contents 和 .children 屬性僅包含標籤的直接子節點，.descendants 屬性可以對所有標籤的子孫節點進行尋找整理。

網頁語法的換行(不是換行的標籤)會造成空白的一個節點。

In [40]:
htmlFile = open('web1.html',encoding="utf8",errors='ignore')
objSoup = bs4.BeautifulSoup(htmlFile, 'html5lib')
for child in  objSoup.body.children:
    print(child)
print("-"*70)




<div class="panel">
    <div class="panel-heading">
        <h4>Hello</h4>	
    </div>
    <div class="panel-body">
        <ul class="list" id="list-1">
            <li class="class1">Foo</li>
            <li class="class1">Bar</li>
            <li class="class1">Jay</li>
        </ul>
        <ul class="list list-small" id="list-2">
            <li class="class2">Foo</li>
            <li class="class2">Bar</li>
        </ul>
    </div>
</div>



<h1>class與id練習測試h1標籤</h1>


<h2>class與id練習測試h2標籤</h2>


<div class="class1">故宮博物院</div>


<div class="class2">日月潭</div>


<div class="class2 class3">阿里山</div>


<div id="id1">士林夜市</div>


<span class="class1">各種</span>
span的
<span class="class3">運用</span>
。

<h2>程式語言清單</h2>


<ol type="I">
   <li>Python</li><li>Java</li><li>C#</li>
</ol>


<h3>以下為圖片
<img src="new1.jpg"/></h3>


<table border="1">
   <thead><!--建立表頭 -->
      <tr><th colspan="3">表格測試</th></tr>
      <tr><th>th1</th><th>th2</th><th>th3</th></tr>
   </thead>
   <tbody><!-- 建立

## 兄弟節點查找

兄弟節點代表與選定的節點處在統一級的節點，如果不存在則傳回 None。

.next_sibling 屬性獲取了該節點的下一個兄弟節點。

.previous_sibling 屬性獲取了這個節點的上一個兄弟節點。

有些網頁的標籤的 .next_sibling 和 .previous_sibling 屬性也可能是空白，因為空白也可以被視作一個節點。

全部兄弟節點：

.next_siblings

.previous_siblings

In [56]:
import bs4
htmlFile = open('web1.html',encoding="utf8",errors='ignore')
objSoup = bs4.BeautifulSoup(htmlFile, 'html5lib')
print(objSoup.p)
print("-----------------------------0---")
print(objSoup.p.next_sibling)#因為有斷行所以是空白節點
print("-----------------------------2---")
print(objSoup.p.next_sibling.next_sibling)
print("-----------------------------3---")
for sibling in objSoup.p.next_siblings:
    if sibling!='\n':
        print(repr(sibling))
print("-----------------------------4---")        
for sibling in objSoup.p.next_siblings:
    if sibling!='\n':
         for text in sibling.stripped_strings:
            print(repr(text))        
        

<p>p標籤0</p>
-----------------------------0---


-----------------------------2---
<p><b>粗體字 p1</b></p>
-----------------------------3---
<p><b>粗體字 p1</b></p>
<p>p標籤2</p>
<p>p標籤3</p>
<h1>h1標籤測試1</h1>
<h1>h1標籤測試2</h1>
<h1>h1標籤測試3</h1>
<h1>h1標籤測試4</h1>
<h2>h2標籤測試1</h2>
<h2>h2標籤測試2</h2>
<h2>h2標籤測試3</h2>
<h2>h2標籤測試4</h2>
<h3>h3標籤測試1</h3>
<h4>h4標籤測試1</h4>
'\n\n\n'
-----------------------------4---
'粗體字 p1'
'p標籤2'
'p標籤3'
'h1標籤測試1'
'h1標籤測試2'
'h1標籤測試3'
'h1標籤測試4'
'h2標籤測試1'
'h2標籤測試2'
'h2標籤測試3'
'h2標籤測試4'
'h3標籤測試1'
'h4標籤測試1'


In [64]:
import requests
from bs4 import BeautifulSoup
url = "https://zh.wikipedia.org/zh-tw/2023年电影"
resp = requests.get(url)
resp.encoding = "utf-8"
#print(resp.text)
soup = BeautifulSoup(resp.text,"html5lib")
movieTable = soup.find("table",class_="wikitable sortable")
tbody = movieTable.find("tbody")
trList = tbody.find_all("tr")
for inx in range(1,len(trList)):
    print(trList[inx].find("th").text,end="")
    print(trList[inx].find("a").text)
    print(trList[inx].find_all("td")[2].text)

1
Barbie芭比
$1,441,809,423

2
超級瑪利歐兄弟電影版
$1,361,427,971

3
奧本海默
$951,386,780

4
星際異攻隊3
$845,555,777

5
玩命關頭X
$704,709,660

6
蜘蛛人：穿越新宇宙
$690,516,673

7
滿江紅
$673,556,758

8
流浪地球2
$604,456,556

9
小美人魚
$569,626,289

10
不可能的任務：致命清算 第一章
$567,535,383



## Numpy簡介

In [66]:
import numpy as np
c1 = [1,3,5,7,9]
d1 = [3,5,6,7,9]
f1 = c1 + d1
print(f1)
c2 = np.array(c1)
d2 = np.array(d1)
f2 = c2 + d2
print(f2)

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]
[ 4  8 11 14 18]


+ ndarray.ndim
   + 維度的數量。
+ ndarray.shape
   + 顯示出陣列在每個維度上的整數值。
+ ndarray.size
   + 陣列內元素的總數。
+ ndarray.dtype
   + 用來描述陣列中元素類型的對象。

In [83]:
import numpy as np
i = [[1,2,3],
     [1,2,3]]
a = np.array(i,dtype=np.int8)
print(a.ndim)
print(a.shape)
print(a.shape[0])
print(a.shape[1])
print(a.size)
print(a.dtype)

2
(2, 3)
2
3
6
int8


In [93]:
import numpy as np
a = np.array([6,7,8,9])
b = np.arange(4)
print(b)
print(type(b))
c = a - b
print(c)
d = b ** 2
print(d)
f = np.array([5,-1,3,9,0])
print(f<=3)
print(f[f<=3] )
f[f<=3] = 1
print(f)

[0 1 2 3]
<class 'numpy.ndarray'>
[6 6 6 6]
[0 1 4 9]
[False  True  True False  True]
[-1  3  0]
[5 1 1 9 1]


## 陣列初始化與重新規劃
+ 針對初始化這部分提供了多種方式：
+ 不做初始化
   + 例如：np.empty((2,4))
+ 全部規劃為 0
   + 例如：np.zeros((3,4))
+　全部規劃為 1
  + np.ones((5,2))
+ 全部規劃／填滿為某數，例如 6
   + 例如： np.full((3,3),6)
+ 建立對角矩陣，對角皆為 1，其他為 0
   + 例如： np.eye(3)
+ 建立對角矩陣，對角為 1,2,3,4，其他為 0
   + 例如： np.diag([1,2,3,4])
+ reshape((x,y)) 這個指令就可以將現有的陣列  重新規劃為 x 乘以 y 的陣列。 
+ np.arange(起始值, 結束值, 固定間隔)：也是產生一維陣列，和 np.array( ) 的差別在於 arange 擁有較大的彈性，而且元素數值是自動化產生。
+ np.linspace(起始值, 結束值, 起始與結束的區間內要產生幾個元素 )：只要給定陣列的區間(起始值、結束值)，就可以要求在這個區間內產生幾個元素。
+ arange(a,b,c)
   + 不包含 b 由 a 開始 以固定間隔 c 來取值
+ linspace(a,b,c,)
   + 包含 b 由 a 開始 切割成 c 個資料
+ linspace(a,b,c,endpoint=False)
   + 不包含 b 由 a 開始 切割成 c 個資料

In [99]:
import numpy as np
x = np.empty((3,4))
print(x)
print("==========================")
x = np.zeros((3,4))
print(x)

[[1.01633934e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.01431399e-311 3.63822111e+175 6.70964262e+170 7.24923947e+169]
 [8.00378332e+169 2.64530589e+180 4.43201525e+175 2.23016117e+160]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [105]:
import numpy as np
x = np.ones((2,4))
print(x)
print("====="*10)
x = np.full((2,4),6)
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6 6 6 6]
 [6 6 6 6]]


In [107]:
import numpy as np
x = np.eye(3)
print(x)
x = np.diag([1,2,3,4])
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### linspace arange

In [122]:
import numpy as np
x = np.linspace(1,10,6)
print(x)
print("================")
x = np.linspace(1,10,6).reshape((3,2))
print(x)
print("================")
x = np.linspace(1,10,6,endpoint=False)#不包含10
print(x)
print("=======")
x = np.arange(8)
print(x)
x = np.arange(8).reshape((4,2))
print(x)

[ 1.   2.8  4.6  6.4  8.2 10. ]
[[ 1.   2.8]
 [ 4.6  6.4]
 [ 8.2 10. ]]
[1.  2.5 4.  5.5 7.  8.5]
[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [123]:
import numpy as np
r1 = np.arange(25, 30, .5)
print("r1=>",r1)

r1=> [25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [124]:
import numpy as np
lin = np.linspace(3, 5, 9)
print("r1=>",lin)

r1=> [3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]


## 陣列指定位置取值
+ 間隔選取 [::c]
  + 以 1 維陣列來說明 x[a:b:c]
  + a：選取資料的起始索引
  + b：選取資料的結束索引 +1
  + c：選取資料間隔，以索引值可以被此值整除的元素，不指定表示 1
+ 倒序 [::-1]
  + 只是單純的把順序反過來

## 陣列指定位置-給予一個整數
+ 關於指定位置  [row,column]
+ 假設給予一個整數為 N
 + 如果是給固定的 N，那就代表 row 或 column 等於 N。
 + 如果是 N：，那就代表 row 或 column 大於等於 N 的區域。
 + 如果是：N，那就代表 row 或 column 小於 N 的區域。 
 + 如果是：，那就代表 row 或 column 是任意欄位。

In [133]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[0])
print(a[2][2])
print(a[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
9
6


In [148]:
import numpy as np
a = np.arange(1,10).reshape((3,3))
print(a)
print(a[1,1:3])
print("==="*10)
print(a[:,1])
print(a[:,1].reshape(3,1))
print("==="*10)
a[1,2] = 75
print(a)
print("==="*10)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]
[2 5 8]
[[2]
 [5]
 [8]]
[[ 1  2  3]
 [ 4  5 75]
 [ 7  8  9]]


In [153]:
import numpy as np
a=np.arange(0,36).reshape((6,6))
print(a)
print("---1--")
print(a[0,3:5])
print("---2--")
print(a[4:,4:])
print("---3--")
print(a[:3,:3])
print("---4--")
print(a[:,2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
---1--
[3 4]
---2--
[[28 29]
 [34 35]]
---3--
[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]
---4--
[ 2  8 14 20 26 32]


## 重設新陣列
+ resize 這個動作會依據原本的陣列再設定指定大小的新陣列。 
+ resize 動作的參數如下：
+ numpy.resize(arr1，shape1)
  + arr1：原本的陣列
  + shape1：新規劃的大小
+ 如果規劃的新陣列比較大，將會重新複製原有陣列的資料，填滿新的儲存格。
+ resize 這個動作***建立新的陣列***，而 reshape 則是依據原有的重新規劃，仍會受到原有陣列影響。
+ transpose()轉置

In [154]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
print(a.shape)
print()
b = a.reshape(3,2)
print(b)
print(b.shape)
a[0,1] = 100
print(b) # 會改變
print(b.shape)
print(a.shape)

(2, 3)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[  1 100]
 [  3   4]
 [  5   6]]
(3, 2)
(2, 3)
